- hosts: all
  tasks:
    - name: Updating repositories
      become: yes
      apt:
        update_cache: yes
    - name: Upgrading packages
      become: yes
      apt:
        name: "*"
        state: latest
    - name: Installing required linux package required in this project
      become: yes
      apt:
        autoclean: yes
        autoremove: yes
        install-recommends: no
        name:
          - curl
          - autoconf
          - bison
          - build-essential
          - libssl-dev
          - libyaml-dev
          - libreadline6-dev
          - zlib1g-dev
          - libncurses5-dev
          - libffi-dev
          - libgdbm6
          - libgdbm-dev
          - libdb-dev
          - mysql-server
          - libmysqlclient-dev
          - python3-mysqldb
    - name: Install rbenv
      shell: curl -fsSL https://github.com/rbenv/rbenv-installer/raw/HEAD/bin/rbenv-installer | bash
    - name: Install ruby version 3.0.1
      shell: /home/gbe01058/.rbenv/bin/rbenv install 3.0.1 -s
    - name: setting ruby version 3.0.1 as global
      shell: /home/gbe01058/.rbenv/bin/rbenv global 3.0.1
    - name: Install gem sinatra and mysql2
      shell: /home/gbe01058/.rbenv/shims/gem install sinatra thin mysql2
    - name: Create database user 'gbe01058' and password 'gbe01058' with all previlages
      become: yes
      mysql_user:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: gbe01058
        password: gbe01058
        priv: "*.*:ALL"
    - name: Create database 'simple_twitter_ruby'
      mysql_db:
        login_user: gbe01058
        login_password: gbe01058
        name: simple_twitter_ruby
    - name: Cloning 'app repo'
      git:
        force: yes
        dest: /home/gbe01058/app
        repo: https://github.com/fajarmuslim/simple_twitter_ruby.git
    - name: Importing 'simple_twitter_ruby.sql'
      mysql_db:
        login_user: gbe01058
        login_password: gbe01058
        name: simple_twitter_ruby
        state: import
        target: /home/gbe01058/app/db/simple_twitter_ruby.sql
    - name: Move 'sinatra.service' file to '/etc/systemd/system/'
      become: yes
      shell:
        cmd: mv /home/gbe01058/app/sinatra.service /etc/systemd/system/
    - name: Reload Daemon
      become: yes
      systemd:
        daemon-reload: true
    - name: Enabling sinatra application
      become: yes
      systemd:
        enabled: yes
        name: sinatra
        force: true
    - name: Starting sinatra application
      become: yes
      systemd:
        name: sinatra
        state: restarted